### PR TITLE
Daniel

### PR DESCRIPTION
**Pull request by djdunning**
Latest update on the build scripts. Adding arguments to remove different solver-based script directories. Make all arguments optional. If we're happy with how it looks, I'll add a final commit updating the README

### CODE REVIEW

**Review by yencal — APPROVED** [review]
Looks good to me. Thanks

**Comment by Adrian-Diaz** [comment]
What motivated moving the project command on the mesh builder?

**Comment by djdunning** [comment]
Ah that's just a bad merge it seems, that was an old fix that it seems to have chosen. I'll revert that

**Comment by Adrian-Diaz** [comment]
There also seems to be a change for a user strength model interface file, was that intentional?

**Comment by yencal** [comment]
> There also seems to be a change for a user strength model interface file, was that intentional?

I believe you are referring to this line
`//cmd.nn = {N1,N2,N3};`

it is no longer needed for EVPFFT-Fierro linkage

**Comment by djdunning** [comment]
@yencal Do you mean that that line is no longer needed so it can stay commented or commenting it out is no longer needed, so it should stay?

**Comment by yencal** [comment]
> @yencal Do you mean that that line is no longer needed so it can stay commented or commenting it out is no longer needed, so it should stay?

@djdunning . that line is no longer needed. it can be deleted.

**Pull request merged**
