### PR TITLE
ENH: Added yaml workflow files for testing installation of Fierro via anaconda and some example input, for the purpose of CI

### PR DESCRIPTION
**Pull request by zacharyjbaker**
# Description

ENH: Added yaml workflow files for testing installation of Fierro via anaconda and some example input, for the purpose of CI

Fierro Test triggers whenever a publishing workflow is run. No reversion functionality, for now we decided to do reversions manually through Client CLI in the case of a failed test.

Publish All workflow currently not functional as `workflow_call:` must be added to each publish yaml file, but I don't want to create 10 pull requests to do that.

## Type of change

Please select all relevant options

- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Formatting and/or style fixes
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [x] Test A : The workflows trigger on a push to main, and should successfully run the parallel-explicit, mesh, and parallel-implicit commands with the listed example inputs (implicit takes a very long time)
- [ ] Test B : 

**Test Configuration**:
* OS version:
* Hardware:
* Compiler:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] The code builds from scratch with my new changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Adrian-Diaz — APPROVED** [review]

**Review by djdunning — APPROVED** [review]
Looks good on my end. Do we know why the implicit solver takes so much longer? I didn't think it should, maybe it was just a testing anomaly.

**Comment by Adrian-Diaz** [comment]
> Looks good on my end. Do we know why the implicit solver takes so much longer? I didn't think it should, maybe it was just a testing anomaly.

Its performing an optimization run with that yaml file

**Comment by nathanielmorgan** [comment]
Lets make this CI workflow run when we deploy a new conda distributions

**Comment by jacob-moore22** [comment]
This is great. The only tweak is to change it to test only after publishing the Conda packages instead of on each push.

**Comment by Adrian-Diaz** [comment]
Ideally it would build a separate version and test but not publish. We should just manually tell it to publish when it's safe to do so.

**Review by Adrian-Diaz — APPROVED** [review]

**Review by nathanielmorgan — COMMENTED** [review]
Looks good.  Having CI of anaconda is great.

**Pull request merged**
