### PR TITLE
Cmake projects

### PR DESCRIPTION
**Pull request by kpwelsh**
Previously we would find the Trilinos packages and then go on to include other sub-directories. Then we would set the CMAKE_CXX_COMPILER to the Trilinos compiler. 

The CMAKE `project` command creates the configuration for the build system and caches the variables. For some variables (CMAKE_CXX_COMPILER is one), invoking the `project` command after changing the variable requires a dump of the CMakeCache file. This is most commonly experienced when the user runs `cmake .. -DCMAKE_CXX_COMPILER=...` after already running `cmake`, but in our case the failure is scripted. 

If those sub-directories contained a `project` command, it would cause a dump and rebuild of the cache file, but with the user inputs dropped. Because the "sub projects" were implicitly dependent on finding Trilinos, it would build those projects without the user input and if Trilinos was not on the path, it would fail to find them.

This change demonstrates how we should be doing sub-projects going forward. The `project` command *should* be used in CMake sub-projects, as suggested by the CMake documentation: "Typically the subdirectory should contain its own [project()](https://cmake.org/cmake/help/latest/command/project.html#command:project) command invocation...". This allows people to build and test sub-projects standalone if they are.

However, we need to be slightly mindful of what we put at which project level. In this case, Trilinos should be lower.

### CODE REVIEW

**Comment by Adrian-Diaz** [comment]
I remember there being some issue where having the project command in our subdirectories would cause an endless loop for CMake.

**Comment by kpwelsh** [comment]
It is possible to create an infinite loop using project commands in sub-projects. The issue almost exclusively occurs when you set CMAKE_*_COMPILER in one of the projects. 

The easiest way to avoid that is to not do that in a CMake script, but instead set it as a user variable upfront (cmake -DCMAKE_CXX_COMPILER=...). The trilinos build instructions tell us to set CMAKE_CXX_COMPILER=TRILINOS_CXX_COMPILER in our scripts, but it is isn't necessary except for fringe workflows. 

The other way to avoid this is to be careful where you set it. Which is what we are doing here.

In general, if we have things that could reasonably be standalone CMake projects (i.e. libraries or independent tools), using project() is appropriate and wont cause issues. If we have highly coupled sub-directories (i.e. Parallel-Explicit + Parallel-Implicit being coupled to Parallel-Base) the project command doesn't make much sense.

**Comment by djdunning** [comment]
Does that mean we should take out the `project()` command inside of the Parallel-Solver/CMakeLists.txt? Or is that fine there

**Comment by Adrian-Diaz** [comment]
Is there an intent to use a different CXX compiler for different parts of the build?

**Comment by djdunning** [comment]
Well we definitely need mpi wrapper for Trilinos. Is there a defect in have them be the compiler for everything?

**Comment by kpwelsh** [comment]
We need mpicxx when compiling Parallel-Solvers, obviously, but the other things don't have any specific compiler requirements.

Modern CMake recommendations suggest *not* setting CMAKE_CXX_COMPILER after the first 'project' command. This is because the project command will look at CMAKE_CXX_COMPILER as well as CXX and configure the project with that compiler. Changing it afterwards could potentially be a significant issue, although commonly it isn't.

Im actually not even really sure what we are getting with the `set(CMAKE_CXX_COMPILER ${TRILINOS_CXX_COMPILER})` though. I have been compiling Fierro this whole time with a different compiler from Trilinos and haven't had any issues.

**Comment by Adrian-Diaz** [comment]
Well, the compilers are probably the same in our case where we built Trilinos with the same environment setup, what may be different is the flags that were used. Where it'd be a problem is if maybe there were different available compilers CMake could find.

**Comment by djdunning** [comment]
I'm not sure how this is possible @kpwelsh . How were you running mpi code without the mpi compiler? At best, I imagine that's a drop in performance

**Comment by kpwelsh** [comment]
@djdunning I am not running the MPI code without an MPI compiler. Its just not the same compiler that was used to build Trilinos. 

I typically run with a Trilinos that was built a while ago and is distributed on our Anaconda distributions, and was compiled on another machine even (sometimes). When I compile things locally against those, I do so with various compiler versions depending on what happens to be in the environment at the time. (this is why I put in the check for compiler existence).

**Comment by Adrian-Diaz** [comment]
what happens when the CXX_Compiler flag is set in multiple subfolders with their respective project commands at the top?

**Comment by kpwelsh** [comment]
Ok. Ive done some more careful experimenting and determined the following:

Build Systems -- 
When you invoke the `project` command, CMake determines the build system. At this point CMAKE_CXX_COMPILER is read and is cached. This, among a couple of other foundational things, determine the actual make commands that are going to be invoked.

Dependent processes -- 
If you have targets in an add_subdirectory call that are dependencies of other targets (in an add_subdirectory or otherwise), CMake tries to ensure those things are using the same build system. If they end up using different build systems, this is where infinite loops can occur as CMake attempts to resolve the build system dependency.

What this means is that setting CMAKE_CXX_COMPILER *after* a `project` command is undefined behavior, since the build system is already set. (read: https://gitlab.kitware.com/cmake/community/-/wikis/FAQ#how-do-i-use-a-different-compiler).
Generally, in our case this happens to work right now and set the compiler as mpicxx. 

CMake only supports **one** compiler per language, and technically only supports specifying that compiler before any `project` command. It is possible to create an infinite loop if you do effectively change the CXX_COMPILER before a sub directory `project` command, since then CMake has to reconfigure the build system.

Also -- FWIW all `mpicxx` does as a compiler wrapper is add linking and include commands to the compiler invocation. Since we already do the

**Comment by Adrian-Diaz** [comment]
Does this apply to the very first project command at the top level? How would we set CXX_Compiler?

**Comment by kpwelsh** [comment]
Yes. It does. 

if you check out that link there are 2 recommended ways, the environment variables or by passing -DCMAKE_CXX_COMPILER. Neither of which is compatible with the recommendation from Trilinos to set it in the CMakeLists.txt.

The third way that is not recommended, but is supported is to set it before the first project command.

**Comment by djdunning** [comment]
@Adrian-Diaz Do you know the repercussions of just having `-DCMAKE_CXX_COMPILER=mpicxx` at our command line? Is there a possibility that Trilinos would present a different one when we currently use `set(CMAKE_CXX_COMPILER ${Trilinos_CXX_COMPILER})`

**Comment by Adrian-Diaz** [comment]
Not sure, and we'd have to dig to get that variable without using the find package command. I wonder if this issue was introduced with CMake patches over the years since the Trilinos devs worked it, it changes quite quickly.

**Comment by kpwelsh** [comment]
Just to be clear -- despite the UB, it *does* happen to work as intended currently.

And Im sure we are all on the same page that we should not try to find that variable ourselves. 

Also, while technically we are setting the CMAKE_CXX_COMPILER to the one Trilinos used, we are both likely using an MPI compiler wrapper, so the *real* compiler we are using is entirely controlled by OMPI_CXX, which we set elsewhere. So currently we aren't even attempting to automatically set our CXX compiler to the compiler that Trilinos used.

**Comment by Adrian-Diaz** [comment]
Hmmm, does it matter if a scenario like Trilinos was compiled with mvapich and Fierro picks up openmpi occurs?

**Comment by kpwelsh** [comment]
It depends on exactly what the different implementations produce. 

If they all produce "mpicxx" and "libmpi" then two can't simultaneously be available in the system + the linker doesn't know the difference. If Trilinos is statically linked, it will create a static archive, but it wont contain definitions for symbols contained in linked shared libraries. So when compiling Fierro we will still dynamically look for symbols we need in the libmpi we find when compiling fierro.

If they produce different things, like something not called "libmpi", then it is possible the Trilinos compile flags will add something like "-lmpich" (for example). In this case, we will be adding our own "-lmpi". Im not 100% sure on the resolution order, but if they provide all of the same symbols (which they do since we can compile against either of them), then one of the will be picked (provided both are available to link against at compile time).

I don't think this is a particularly valid workflow, and can easily be corrected by unloading the different MPI implementation if there is an issue.

**Comment by Adrian-Diaz** [comment]
So, the bottom line for approving this. Does having CXX set in the parallel-solvers sub project avoid the infinite loop if someone has a sub project in another directory that set CXX? otherwise this may make for a bad example.

**Comment by kpwelsh** [comment]
@Adrian-Diaz 

```cmake
set(CMAKE_CXX_COMPILER ...)
project(...)
```
In a sub-project causes an infinite loop or breaks (depending on the other projects being configured). I also don't see a valid workflow where someone is hard-coding the compiler like this.

```cmake
project(...)
set(CMAKE_CXX_COMPILER ...)
```
Isn't supposed to do anything at all and is not supposed to be a valid CMake script\*. The only reason we do it with Trilinos is because that's what they have on their example CMake script. If someone does this in a sub-project, it is _possible_ that CMake will use that compiler if configuring that project alone, but it definitely wont if we are building it from the top and have otherwise configured the compiler. 


\* I just removed the project call from the parallel-src directory, as I noticed we weren't actually setting the compiler to mpicxx if the `project` call is in there. Not that I think that's a problem...

**Comment by Adrian-Diaz** [comment]
Won't pushing that setting down a directory lead to issues later if someone makes another standalone app that requires Trilinos?

**Comment by kpwelsh** [comment]
If its supposed to be available standalone, wouldn't that app just find_package(Trilinos) and do the same thing?

**Review by Adrian-Diaz — APPROVED** [review]
Should be fine.

**Pull request merged**
