### PR TITLE
Fix q2 gradient term and move yaml file out of spurious directory

### PR DESCRIPTION
**Pull request by Adrian-Diaz**
# Description

## Type of change

Please select all relevant options

- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Formatting and/or style fixes
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [x] Test A : 
- [ ] Test B : 

**Test Configuration**:
* OS version:
* Hardware:
* Compiler:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] The code builds from scratch with my new changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by jacob-moore22** [comment]
Two things:
- Run uncrustify
- Note if the integrated tests still pass. They should, but always worth checking.

**Review by djdunning — APPROVED** [review]
Looks good to me, although I don't know the magnitude of all the numerical changes (e.g. the input file)

**Comment by jacob-moore22** [comment]
> Looks good to me, although I don't know the magnitude of all the numerical changes (e.g. the input file)

His changes add second order damping to the input file, which generally gives better solutions with less ringing.

**Review by jacob-moore22 — APPROVED** [review]
lgtm

**Pull request merged**
